// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard/Current.tsx": () => import("../components/mockups/dashboard/Current.tsx"),
  "./components/mockups/dashboard/Fieldbook.tsx": () => import("../components/mockups/dashboard/Fieldbook.tsx"),
  "./components/mockups/dashboard/WorldClass.tsx": () => import("../components/mockups/dashboard/WorldClass.tsx")
};
